[package]
name = "bmv"
version = "0.1.1"
authors = ["Pontus Laos <laos.pontus@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0.0-beta.2", features = ["color"] }
